name: ClipFlow
options:
  bundleIdPrefix: com
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES

targets:
  ClipFlow:
    type: application
    platform: macOS
    sources:
      - path: ClipFlow
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ClipFlow.app
        INFOPLIST_FILE: ClipFlow/Info.plist
        PRODUCT_NAME: ClipFlow
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        SWIFT_EMIT_LOC_STRINGS: YES
        CODE_SIGN_ENTITLEMENTS: ClipFlow/ClipFlow.entitlements
    info:
      path: ClipFlow/Info.plist
      properties:
        CFBundleName: ClipFlow
        CFBundleDisplayName: ClipFlow
        CFBundleIdentifier: com.ClipFlow.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: ClipFlow
        LSMinimumSystemVersion: "13.0"
        NSHumanReadableCopyright: Copyright © 2024. All rights reserved.
        NSPrincipalClass: NSApplication
